services:
   backend:
      build: 
         context: .
         dockerfile: Dockerfile.backend
      container_name: messaging-backend
      ports:
         - "8080:8080"

   ui:
      build: ./messaging-ui
      container_name: messaging-ui
      ports:
         - "8081:80"
      depends_on:
         - backend