name: Docker images publisher

on:
  push:
    tags:
      - "v*.*.*" # triggers on tags like v1.0.0

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_OWNER: ${{ github.repository_owner }}
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (API)
        id: meta_api
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/${{ env.REPO_NAME }}-api
          tags: |
            type=ref,event=tag
            type=raw,value=latest

      - name: Extract metadata (UI)
        id: meta_ui
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/${{ env.REPO_NAME }}-ui
          tags: |
            type=ref,event=tag
            type=raw,value=latest

      - name: Build and push (UI)
        uses: docker/build-push-action@v6
        with:
          context: ./messaging-ui
          file: ./messaging-ui/Dockerfile
          push: true
          tags: ${{ steps.meta_ui.outputs.tags }}
          labels: ${{ steps.meta_ui.outputs.labels }}